version: "3.8"

services:

  db:
    image: mysql
    ports:
      - 3306:3306
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - "./db/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/data.sql:/docker-entrypoint-initdb.d/2.sql"
    env_file:
      - ./.env

  backend:
    build: backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on: 
      - db
  
  ui:
    build: ui
    ports:
      - 80:80
    depends_on: 
      - backend

volumes:
  db-data:

